const iconMap: { [key: string]: string } = {
  // Main icons
  github: 'fab fa-github',
  linkedin: 'fab fa-linkedin',
  twitter: 'fab fa-x-twitter',
  instagram: 'fab fa-instagram',
  envelope: 'fas fa-envelope',
  globe: 'fas fa-globe',
  'book-open': 'fas fa-book-open',
  'file-text': 'fas fa-file-text',
  palette: 'fas fa-palette',
  'th-large': 'fas fa-th-large',
  user: 'fas fa-user',
  play: 'fas fa-play',
  'graduation-cap': 'fas fa-graduation-cap',
  handshake: 'fas fa-handshake',
  music: 'fas fa-music',
  youtube: 'fab fa-youtube',
  'external-link-alt': 'fas fa-external-link-alt',
  sun: 'fas fa-sun',
  moon: 'fas fa-moon',
  folder: 'fas fa-folder',
  dribbble: 'fab fa-dribbble',
  behance: 'fab fa-behance',

  // Legacy uppercase support
  Phone: 'fas fa-phone',
  Location: 'fas fa-map-marker-alt',
  Calendar: 'fas fa-calendar',
  Clock: 'fas fa-clock',
  Users: 'fas fa-users',
  Heart: 'fas fa-heart',
  Star: 'fas fa-star',
  Bookmark: 'fas fa-bookmark',
  Tag: 'fas fa-tag',
  Flag: 'fas fa-flag',
  Award: 'fas fa-award',
  Trophy: 'fas fa-trophy',
  Gift: 'fas fa-gift',
  Camera: 'fas fa-camera',
  Image: 'fas fa-image',
  Video: 'fas fa-video',
  Headphones: 'fas fa-headphones',
  Microphone: 'fas fa-microphone',
  Volume: 'fas fa-volume-up',
  Download: 'fas fa-download',
  Upload: 'fas fa-upload',
  Share: 'fas fa-share',
  Link: 'fas fa-link',
  External: 'fas fa-external-link-alt',
  Copy: 'fas fa-copy',
  Edit: 'fas fa-edit',
  Delete: 'fas fa-trash',
  Settings: 'fas fa-cog',
  Tools: 'fas fa-tools',
  Wrench: 'fas fa-wrench',
  Hammer: 'fas fa-hammer',
  Lightning: 'fas fa-bolt',
  Battery: 'fas fa-battery-full',
  Wifi: 'fas fa-wifi',
  Bluetooth: 'fab fa-bluetooth',
  Monitor: 'fas fa-desktop',
  Mobile: 'fas fa-mobile-alt',
  Tablet: 'fas fa-tablet-alt',
  Laptop: 'fas fa-laptop',
  Storage: 'fas fa-hdd',
  Database: 'fas fa-database',
  Server: 'fas fa-server',
  Cloud: 'fas fa-cloud',
  facebook: 'fab fa-facebook',
  Twitch: 'fab fa-twitch',
  Discord: 'fab fa-discord',
  Email: 'fas fa-envelope',
  'X (Twitter)': 'fab fa-x-twitter',
  Telegram: 'fab fa-telegram',
  TikTok: 'fab fa-tiktok',
  Spotify: 'fab fa-spotify',
  Snapchat: 'fab fa-snapchat',
  WhatsApp: 'fab fa-whatsapp',
  Reddit: 'fab fa-reddit',
  // Social platform icons from create page
  email: 'fas fa-envelope',
  'x-twitter': 'fab fa-x-twitter',
  telegram: 'fab fa-telegram',
  tiktok: 'fab fa-tiktok',
  spotify: 'fab fa-spotify',
  snapchat: 'fab fa-snapchat',
  whatsapp: 'fab fa-whatsapp',
  reddit: 'fab fa-reddit',
  // Lowercase versions
  phone: 'fas fa-phone',
  location: 'fas fa-map-marker-alt',
  calendar: 'fas fa-calendar',
  clock: 'fas fa-clock',
  users: 'fas fa-users',
  heart: 'fas fa-heart',
  star: 'fas fa-star',
  bookmark: 'fas fa-bookmark',
  tag: 'fas fa-tag',
  flag: 'fas fa-flag',
  award: 'fas fa-award',
  trophy: 'fas fa-trophy',
  gift: 'fas fa-gift',
  camera: 'fas fa-camera',
  image: 'fas fa-image',
  video: 'fas fa-video',
  headphones: 'fas fa-headphones',
  microphone: 'fas fa-microphone',
  volume: 'fas fa-volume-up',
  download: 'fas fa-download',
  upload: 'fas fa-upload',
  share: 'fas fa-share',
  link: 'fas fa-link',
  external: 'fas fa-external-link-alt',
  copy: 'fas fa-copy',
  edit: 'fas fa-edit',
  delete: 'fas fa-trash',
  settings: 'fas fa-cog',
  tools: 'fas fa-tools',
  wrench: 'fas fa-wrench',
  hammer: 'fas fa-hammer',
  lightning: 'fas fa-bolt',
  battery: 'fas fa-battery-full',
  wifi: 'fas fa-wifi',
  bluetooth: 'fab fa-bluetooth',
  monitor: 'fas fa-desktop',
  mobile: 'fas fa-mobile-alt',
  tablet: 'fas fa-tablet-alt',
  laptop: 'fas fa-laptop',
  storage: 'fas fa-hdd',
  database: 'fas fa-database',
  server: 'fas fa-server',
  cloud: 'fas fa-cloud',
  twitch: 'fab fa-twitch',
  discord: 'fab fa-discord',
  // Legacy support
  Github: 'fab fa-github',
  Linkedin: 'fab fa-linkedin',
  Twitter: 'fab fa-x-twitter',
  Instagram: 'fab fa-instagram',
  Mail: 'fas fa-envelope',
  Globe: 'fas fa-globe',
  BookOpen: 'fas fa-book-open',
  FileText: 'fas fa-file-text',
  Palette: 'fas fa-palette',
  Layout: 'fas fa-th-large',
  User: 'fas fa-user',
  Play: 'fas fa-play',
  GraduationCap: 'fas fa-graduation-cap',
  Handshake: 'fas fa-handshake',
  Music: 'fas fa-music',
  Youtube: 'fab fa-youtube',
  ExternalLink: 'fas fa-external-link-alt',
  Sun: 'fas fa-sun',
  Moon: 'fas fa-moon',
  Folder: 'fas fa-folder',
  Dribbble: 'fab fa-dribbble',
  Behance: 'fab fa-behance'
}

interface IconProps {
  name: string
  className?: string
}

export default function IconComponent({ name, className = "" }: IconProps) {
  // Normalize icon name to handle case variations
  const normalizedName = name ? name.toLowerCase().trim() : 'globe'
  const iconClass = iconMap[normalizedName] || iconMap[name] || iconMap.globe || 'fas fa-globe'
  return <i className={`${iconClass} ${className}`} />
}